### PR TITLE
fix: unused err

### LINKED ISSUE #280: Unused variable err
This should be handled properly:
https://github.com/twitchdev/twitch-cli/blob/6520e9dac52b8e8d0ecd75eb5a5e5db77319570a/internal/login/login_request.go#L28

### PR DESCRIPTION
**Pull request by SputNikPlop**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

## Problem/Feature

There is an err that is unused

## Description of Changes: 

- Fixes #280 

## Checklist

- [x] My code follows the [Contribution Guide](https://github.com/twitchdev/twitch-cli/blob/master/CONTRIBUTING.md#Requirements)
- [x] I have self-reviewed the changes being requested
- [x] I have made comments on pieces of code that may be difficult to understand for other editors
- [x] I have updated the documentation (if applicable)

### CODE REVIEW

File: internal/login/login_request.go [hunk 1]
```diff
@@ -27,6 +27,10 @@ func loginRequest(method string, url string, payload io.Reader) (loginRequestRes
 func loginRequestWithHeaders(method string, url string, payload io.Reader, headers []loginHeader) (loginRequestResponse, error) {
 	req, err := request.NewRequest(method, url, payload)
 
+	if err != nil {
+		return loginRequestResponse{}, nil
```
Comment (Xemdo) [inline internal/login/login_request.go:31]: This should be `return loginRequestResponse{}, err`, to surface the error instead of nil

**Review by Xemdo — CHANGES_REQUESTED** [review]

**Review by Xemdo — APPROVED** [review]
